// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkkdekVOxsoQjeSPTKVMu8R8cySC85SSE',
    appId: '1:247547863779:web:7ff02c7e549f28898a9bd6',
    messagingSenderId: '247547863779',
    projectId: 'tasktodo-40493',
    authDomain: 'tasktodo-40493.firebaseapp.com',
    storageBucket: 'tasktodo-40493.appspot.com',
    measurementId: 'G-RL34H1DH8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxiA2IyvfRhFBPMgODIJTcSvGogZLC_r8',
    appId: '1:247547863779:android:185136f15cd1ff7a8a9bd6',
    messagingSenderId: '247547863779',
    projectId: 'tasktodo-40493',
    storageBucket: 'tasktodo-40493.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfbkypTievXOTxYS2zge2_kJbzdeA4Cx0',
    appId: '1:247547863779:ios:04344a4adf30322a8a9bd6',
    messagingSenderId: '247547863779',
    projectId: 'tasktodo-40493',
    storageBucket: 'tasktodo-40493.appspot.com',
    iosBundleId: 'com.example.taskFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfbkypTievXOTxYS2zge2_kJbzdeA4Cx0',
    appId: '1:247547863779:ios:e10dea2550d160d08a9bd6',
    messagingSenderId: '247547863779',
    projectId: 'tasktodo-40493',
    storageBucket: 'tasktodo-40493.appspot.com',
    iosBundleId: 'com.example.taskFirebase.RunnerTests',
  );
}
